apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: two-tier-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CharanReddy129/two-tier-argocd-repo.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true