apiVersion: apps/v1 
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend 
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: flask-con
          image: 851725275708.dkr.ecr.ap-south-1.amazonaws.com/flask-app:v4
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          env:
            - name: MYSQL_HOST
              value: "mysql-service"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_DB
              value: "mydb"
      # imagePullSecrets:
      #   - name: ecr-registry-secret
